### ISSUE TITLE
Crash in PointcloudPhase from h5py

### ISSUE THREAD

**Issue by turinath** [ATTPC/Spyral#162]
2024-07-11 15:07:31,344 - spyral.core.pipeline - ERROR - Unable to synchronously check link existence (wrong B-tree signature)
Traceback (most recent call last):
  File "/path/to/spyral/spyral/core/pipeline.py", line 203, in run
    result = phase.run(result, self.workspace, msg_queue, rng)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/path/to/spyral_env/spyral-env/lib/python3.11/site-packages/spyral/phases/pointcloud_phase.py", line 215, in run
    if event_name not in event_group:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/path/to/spyral_env/spyral-env/lib/python3.11/site-packages/h5py/_hl/group.py", line 514, in __contains__
    return h5g._path_valid(self.id, self._e(name), self._lapl)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5g.pyx", line 531, in h5py.h5g._path_valid
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5l.pyx", line 212, in h5py.h5l.LinkProxy.exists
RuntimeError: Unable to synchronously check link existence (wrong B-tree signature)

**Comment by gwm17** [comment]
So this isn't from the mesh. It's from the pointcloud_phase, in particular it's h5py complaining about not being able to acquire the lock to a file or even the file itself. I guess probably the first thing I would do to debug this is make sure that the workspace exists and is at the right location. Next I would check to make sure you don't have any notebooks still running with this file loaded.

**Comment by gwm17** [comment]
Marking this as closed as it seems to be unrelated to Spyral itself, and rather related to merging the raw data.
